apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-operator
  labels:
    control-plane: kubeflow-training-operator
spec:
  selector:
    matchLabels:
      control-plane: kubeflow-training-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: kubeflow-training-operator
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      imagePullSecrets:
        - name: harbor-platform-readonly-secret
      nodeSelector:
        node-role.kubernetes.io/baai-infra: ""
        node-role.kubernetes.io/baai-infra-ib: ""
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/baai-infra
          operator: Exists
      containers:
        - command:
            - /manager
            - --enable-gang-scheduling=true
          image: harbor-dev.platform.baai-inner.ac.cn/airs-system/business/training-operator
          imagePullPolicy: "Always"
          name: training-operator
          ports:
            - containerPort: 8080
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 1000m
              memory: 100Gi
            requests:
              cpu: 100m
              memory: 10Gi
      serviceAccountName: training-operator
      terminationGracePeriodSeconds: 10
