apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ../../base
  - namespace.yaml
images:
  - name: harbor-dev.platform.baai-inner.ac.cn/baai-third/training-operator/training-operator
    newTag: release-paddle-support
